require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ShortLinksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ShortLink. As you add validations to ShortLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShortLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all short_links as @short_links" do
      short_link = ShortLink.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:short_links)).to eq([short_link])
    end
  end

  describe "GET #show" do
    it "assigns the requested short_link as @short_link" do
      short_link = ShortLink.create! valid_attributes
      get :show, {:id => short_link.to_param}, valid_session
      expect(assigns(:short_link)).to eq(short_link)
    end
  end

  describe "GET #new" do
    it "assigns a new short_link as @short_link" do
      get :new, {}, valid_session
      expect(assigns(:short_link)).to be_a_new(ShortLink)
    end
  end

  describe "GET #edit" do
    it "assigns the requested short_link as @short_link" do
      short_link = ShortLink.create! valid_attributes
      get :edit, {:id => short_link.to_param}, valid_session
      expect(assigns(:short_link)).to eq(short_link)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ShortLink" do
        expect {
          post :create, {:short_link => valid_attributes}, valid_session
        }.to change(ShortLink, :count).by(1)
      end

      it "assigns a newly created short_link as @short_link" do
        post :create, {:short_link => valid_attributes}, valid_session
        expect(assigns(:short_link)).to be_a(ShortLink)
        expect(assigns(:short_link)).to be_persisted
      end

      it "redirects to the created short_link" do
        post :create, {:short_link => valid_attributes}, valid_session
        expect(response).to redirect_to(ShortLink.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved short_link as @short_link" do
        post :create, {:short_link => invalid_attributes}, valid_session
        expect(assigns(:short_link)).to be_a_new(ShortLink)
      end

      it "re-renders the 'new' template" do
        post :create, {:short_link => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested short_link" do
        short_link = ShortLink.create! valid_attributes
        put :update, {:id => short_link.to_param, :short_link => new_attributes}, valid_session
        short_link.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested short_link as @short_link" do
        short_link = ShortLink.create! valid_attributes
        put :update, {:id => short_link.to_param, :short_link => valid_attributes}, valid_session
        expect(assigns(:short_link)).to eq(short_link)
      end

      it "redirects to the short_link" do
        short_link = ShortLink.create! valid_attributes
        put :update, {:id => short_link.to_param, :short_link => valid_attributes}, valid_session
        expect(response).to redirect_to(short_link)
      end
    end

    context "with invalid params" do
      it "assigns the short_link as @short_link" do
        short_link = ShortLink.create! valid_attributes
        put :update, {:id => short_link.to_param, :short_link => invalid_attributes}, valid_session
        expect(assigns(:short_link)).to eq(short_link)
      end

      it "re-renders the 'edit' template" do
        short_link = ShortLink.create! valid_attributes
        put :update, {:id => short_link.to_param, :short_link => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested short_link" do
      short_link = ShortLink.create! valid_attributes
      expect {
        delete :destroy, {:id => short_link.to_param}, valid_session
      }.to change(ShortLink, :count).by(-1)
    end

    it "redirects to the short_links list" do
      short_link = ShortLink.create! valid_attributes
      delete :destroy, {:id => short_link.to_param}, valid_session
      expect(response).to redirect_to(short_links_url)
    end
  end

end
